# -*- coding: utf-8 -*-
"""Ashutosh world_Population.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1xDL3UL1N9MBSp6XNtIp0fcHc5MZjD7
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/world_population.csv')

df

print(df.columns)

df.head()

df=pd.read_csv('/content/world_population.csv')

print("First few rows of the dataset:")
print(df.head())

print("\nDataset information:")
print(df.info())

print("\nSummary statistics for numerical columns:")
print(df.describe())

print("\nMissing values:")
print(df.isnull().sum)

print("\nUnique values in categorical columns:")
for column in df.select_dtypes(include='object').columns:
  print(f"{column}: {df[column].unique()}")

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

plt.figure(figsize=(10,6))
plt.title('Population Distribution')
plt.xlabel('population')
plt.ylabel('frequency')
plt.show()

plt.figure(figsize=(10,6))
plt.title('Population Growth Over Time')
plt.xlabel('year')
plt.ylabel('Population')
plt.show()

plt.figure(figsize=(12, 6))
plt.title('Population by Region')
plt.xlabel('Region')
plt.ylabel('Population')
plt.xticks(rotation=45)
plt.show()