# -*- coding: utf-8 -*-
"""Assignment 5 Ashutosh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K52wBfkj_DfYPHzRxW1W3JAX3WaObPeT
"""

#1
def vending_machine(total_candies_to_load):
    while total_candies_to_load > 0:
        num_candies = int(input("How many candies would you like to purchase? "))

        total_amount = num_candies * 1  # Each candy costs 1 dollar

        amount_paid = float(input("Please enter the amount for the candies ($1 each): $"))

        if amount_paid < total_amount:
            print("Insufficient amount paid. Please insert more money.")
        elif amount_paid == total_amount:
            print(f"Here are your {num_candies} candies. Enjoy!")
            total_candies_to_load -= num_candies
        else:
            change = amount_paid - total_amount
            print(f"Here are your {num_candies} candies. Enjoy! And here's your change: ${change:.2f}")
            total_candies_to_load -= num_candies

    print("Candy vending machine is empty. Please refill.")

def main():
    total_candies_to_load = int(input("How many candies to load onto the vending machine? "))
    vending_machine(total_candies_to_load)

if __name__ == "__main__":
    main()

#2
def print_even_and_odd_numbers(start, end):
    print("Even numbers:")
    for num in range(start, end + 1):
        if num % 2 == 0:
            print(num)

    print("\nOdd numbers:")
    for num in range(start, end + 1):
        if num % 2 != 0:
            print(num)

def main():
    start = int(input("Enter the starting number: "))
    end = int(input("Enter the ending number: "))

    print_even_and_odd_numbers(start, end)

if __name__ == "__main__":
    main()

#3
def count_characters(string):
    upper_count = 0
    lower_count = 0
    digit_count = 0
    symbol_count = 0

    for char in string:
        if char.isupper():
            upper_count += 1
        elif char.islower():
            lower_count += 1
        elif char.isdigit():
            digit_count += 1
        else:
            symbol_count += 1

    return upper_count, lower_count, digit_count, symbol_count

def main():
    string = input("Enter a string: ")
    upper_count, lower_count, digit_count, symbol_count = count_characters(string)

    print("Total number of uppercase letters:", upper_count)
    print("Total number of lowercase letters:", lower_count)
    print("Total number of digits:", digit_count)
    print("Total number of symbols:", symbol_count)

if __name__ == "__main__":
    main()

#4
def validate_password(password):
    if password.isalpha():
        return True
    else:
        return False

def main():
    name = input("Enter your name: ")
    password = input("Enter your password: ")

    if validate_password(password):
        print("Form submitted successfully!")
    else:
        print("Error: Password should only consist of alphabets.")

if __name__ == "__main__":
    main()

#5
def is_leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

def main():
    year = int(input("Enter the year to check: "))
    if is_leap_year(year):
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")

if __name__ == "__main__":
    main()