# -*- coding: utf-8 -*-
"""Assignment 4 Ashutosh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IJnthQqv38ipUztLbVmH5V3hdrAEOlRd
"""

#1
def calculate_probability(favorable_outcomes, total_outcomes):
    probability = favorable_outcomes / total_outcomes
    return round(probability, 2)

def main():
    favorable_outcomes = int(input("Enter the number of favorable outcomes: "))
    total_outcomes = int(input("Enter the total number of possible outcomes: "))

    probability = calculate_probability(favorable_outcomes, total_outcomes)

    print("Probability:", probability)

if __name__ == "__main__":
    main()

#2
def check_age(age):
    if age >= 18:
        print("User's age is greater than or equal to 18. Proceed with the next step.")
    else:
        print("User's age is less than 18. Cannot proceed with the registration.")

def main():
    age = int(input("Enter the user's age: "))
    check_age(age)

if __name__ == "__main__":
    main()

#3
name = input("Enter your name:")
print("Hi, My name is Jenni, chatbot.A Very Good Day To You {}.".format(name.capitalize()))
feel = input("How are you feeling today?? ")
if feel.upper() == 'GOOD':
  print("It's really a productive day to do something innovative and you are close to it.")
else:
  print("Don't worry!! you got this {}!!.Buckle up and cheer yourself up. Good days are on their way. There is no beautiful rainbow without a heav.".format(name.capitalize()))

#5
colors = ["red", "blue", "green", "yellow", "orange", "purple", "pink"]

for color in colors:
    if color == "red":
        continue
    print(color)

#6
def simple_interest(principal, rate, time):
    return principal * rate * time / 100

def compound_interest(principal, rate, time):
    return principal * ((1 + rate / 100) ** time - 1)

def main():
    principal = 10000
    rate = 6
    time = 30

    yash_return = simple_interest(principal, rate, time)
    vishal_return = compound_interest(principal, rate, time)

    difference = vishal_return - yash_return

    print("Difference in returns after 30 years:")
    print("Yash's return (Simple Interest): $", round(yash_return, 2))
    print("Vishal's return (Compound Interest): $", round(vishal_return, 2))
    print("Difference: $", round(difference, 2))

    # Calculate difference in returns for one year
    yash_return_one_year = simple_interest(principal, rate, 1)
    vishal_return_one_year = compound_interest(principal, rate, 1)
    difference_one_year = vishal_return_one_year - yash_return_one_year

    print("\nDifference in returns for one year:")
    print("Yash's return (Simple Interest) for one year: $", round(yash_return_one_year, 2))
    print("Vishal's return (Compound Interest) for one year: $", round(vishal_return_one_year, 2))
    print("Difference for one year: $", round(difference_one_year, 2))

if __name__ == "__main__":
    main()

#7
def calculate_tax(annual_income):
    tax = 0
    if annual_income <= 250000:
        tax = 0
    elif 250000 < annual_income <= 500000:
        tax = (annual_income - 250000) * 0.05
    elif 500000 < annual_income <= 1000000:
        tax = 12500 + (annual_income - 500000) * 0.2
    else:
        tax = 112500 + (annual_income - 1000000) * 0.3
    return tax

def main():
    annual_income = float(input("Enter your annual income: "))
    tax = calculate_tax(annual_income)
    print("Tax to be paid: $", round(tax, 2))

if __name__ == "__main__":
    main()

#8
def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    return bmi

def main():
    weight = float(input("Enter your weight in kilograms: "))
    height = float(input("Enter your height in meters: "))

    bmi = calculate_bmi(weight, height)

    print("Your BMI is:", round(bmi, 2))
    if bmi < 18.5:
        print("You are underweight.")
    elif 18.5 <= bmi < 25:
        print("Your weight is in the healthy range.")
    else:
        print("You are overweight.")

if __name__ == "__main__":
    main()

#9
def is_leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    else:
        return False

def main():
    year = int(input("Enter the year to check: "))
    if is_leap_year(year):
        print(f"{year} is a leap year.")
    else:
        print(f"{year} is not a leap year.")

if __name__ == "__main__":
    main()

#4
# Initialize bank balance
bank_balance = 50000

# Function to handle withdrawal
def withdraw(amount):
    global bank_balance
    if amount % 100 == 0:
        if amount <= bank_balance:
            bank_balance -= amount
            print(f"Withdrawn {amount} successfully. Remaining balance: {bank_balance}")
        else:
            print("Insufficient funds!")
    else:
        print("Error: Withdraw amount must be in multiples of 100.")

# Function to handle deposit
def deposit(amount):
    global bank_balance
    bank_balance += amount
    print(f"Deposited {amount} successfully. Updated balance: {bank_balance}")

# Function to show balance enquiry
def balance_enquiry():
    print(f"Your current account balance is: {bank_balance}")

# Function to handle fast cash option
def fast_cash(option):
    global bank_balance
    options = [5000, 10000, 15000, 20000, 25000, 30000, 40000, 45000, 50000]
    if option in options:
        if option <= bank_balance:
            bank_balance -= option
            print(f"Withdrawn {option} as fast cash. Remaining balance: {bank_balance}")
        else:
            print("Insufficient funds!")
    else:
        print("Error: Invalid fast cash option.")

# Function to display ATM options
def atm_options():
    print("ATM Machine Options:")
    print("1) Withdraw")
    print("2) Deposit Cash")
    print("3) Balance Enquiry")
    print("4) Fast Cash")

# Main function to drive the ATM machine
def main():
    atm_options()
    choice = int(input("Enter your choice: "))

    if choice == 1:
        amount = int(input("Enter the amount to withdraw: "))
        withdraw(amount)
    elif choice == 2:
        amount = int(input("Enter the amount to deposit: "))
        deposit(amount)
    elif choice == 3:
        balance_enquiry()
    elif choice == 4:
        option = int(input("Select the fast cash option: "))
        fast_cash(option)
    else:
        print("Error: Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()