# -*- coding: utf-8 -*-
"""Copy of ASHUTOSH KUMAR_MST01_0045_Assignment_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qeLWAj0KgvVYe44Ac9AibBfYxIa0Lo99
"""

print("Arvind")
print("Ashutosh")
age=22
print("My age is:",age)

friends = ["Deva", "Aryan", "Swastik", "David", "Rinkesh"]

print(*friends, sep="\n")

print("     ( )\n    (   )\n   (     )\n  (       )\n (         )\n  ***   ***\n     | |\n     | |\n     | |\n     | |\n    /   \ \n   /     \ \n*************")

# Cost of one notebook
cost_per_notebook = 2

# Get the number of notebooks from the user
num_notebooks = int(input("Enter the number of notebooks to buy: "))

# Calculate the total amount
total_amount = cost_per_notebook * num_notebooks

# Print the total amount
print(f"The total amount to be paid is: ${total_amount}")

name = input("Enter your name:")
age = int(input("Enter your age:"))
resi = input("Enter your address:")
print("My name is " +name+ ". I am " +str(age)+" years old.My address is " +resi)

print("Hi, I am chatBot. What is your name? ")
name = input()
print("Oh,"+name+" in which grade are you right now?")
grade = int(input())
print(name+" you are in " + str(grade)+"th grade.Can I ask you one question? yes or No?")
yes = input("")
print("Tell me 50+50=?")
ans = input("")
print("Good your answer is correct! Bye")
bye = input("")

Number1 = int(input("Enter the first number: "))
Number2 = int(input("Enter the second number: "))
print("Sum of two numbers is: ",Number1 + Number2)
print("Difference of two numbers is: ",Number1 - Number2)
print("Product of two numbers is: ",Number1 * Number2)
print("Division of two numbers is: ",Number1 / Number2)

Present_year = int(input("Enter Present Year:"))
Birth_year = int(input("Enter Birth Year: "))
print("Your age is ",Present_year - Birth_year)